/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperTrunfoDaReciclagem.temp.Grafics;

import SuperTrunfoDaReciclagem.temp.SuperTrunfoDaReciclagem;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class startGame extends javax.swing.JInternalFrame {
    private int aux;
    private boolean information = true;
    /**
     * Creates new form NewJInternalFrame
     */
    public startGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQnt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JButton();
        tuoPane = new javax.swing.JPanel();

        txtQnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade de jogadores:");

        txtQuant.setText("Enviar");
        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tuoPaneLayout = new javax.swing.GroupLayout(tuoPane);
        tuoPane.setLayout(tuoPaneLayout);
        tuoPaneLayout.setHorizontalGroup(
            tuoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        tuoPaneLayout.setVerticalGroup(
            tuoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tuoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuant)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuant))
                .addGap(18, 18, 18)
                .addComponent(tuoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed

    }//GEN-LAST:event_txtQntActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
         aux = txtQnt.getSelectedIndex() + 2;
        //startGame exit = new startGame();
        //SuperTrunfoDaReciclagem selectTrunfo = new SuperTrunfoDaReciclagem();
        //selectTrunfo.setQntJogadores(aux);
        //exit.dispose();
        JOptionPane.showMessageDialog(null, "Quantidade: " + aux);
        dispose();
        
    }//GEN-LAST:event_txtQuantActionPerformed
public int getAux(){
        return aux;
}   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel tuoPane;
    private javax.swing.JComboBox<String> txtQnt;
    private javax.swing.JButton txtQuant;
    // End of variables declaration//GEN-END:variables
}
